$ANSIBLE_VAULT;1.1;AES256
36373264336530646537303965653461363163653638366231343564633036326337353337343032
6466383738336265376565653133393163643335613564620a326131316139653364323032626531
64336339326464636334613833383933343166313365393463376639333839373962643561313963
6330316439653737340a353534343531346630663761646464313631316266363232306334383132
65343865663762393965346536663865313236313830613961313335636236633432